apiVersion: apps/v1
kind: Deployment
metadata:
    name: leaderboards
    namespace: neighborly
    labels:
        app: leaderboards
spec:
    replicas: 1
    selector:
        matchLabels:
            app: leaderboards
    template:
        metadata:
            labels:
                app: leaderboards
        spec:
            containers:
                - name: leaderboards
                  image: ksvcchh/neighborly-leaderboards:latest
                  ports:
                      - containerPort: 3003
                  env:
                      - name: NODE_ENV
                        valueFrom:
                            configMapKeyRef:
                                name: neighborly-config
                                key: NODE_ENV
                      - name: PORT
                        value: "3003"
                      - name: MONGODB_URI
                        valueFrom:
                            configMapKeyRef:
                                name: neighborly-config
                                key: MONGODB_URI
                      - name: USERS_COLLECTION_NAME
                        valueFrom:
                            configMapKeyRef:
                                name: neighborly-config
                                key: USERS_COLLECTION_NAME
                      - name: TASKS_COLLECTION_NAME
                        valueFrom:
                            configMapKeyRef:
                                name: neighborly-config
                                key: TASKS_COLLECTION_NAME
                      - name: LEADERBOARDS_COLLECTION_NAME
                        valueFrom:
                            configMapKeyRef:
                                name: neighborly-config
                                key: LEADERBOARDS_COLLECTION_NAME
                  livenessProbe:
                      httpGet:
                          path: /leaderboards/publishers
                          port: 3003
                      initialDelaySeconds: 30
                      periodSeconds: 10
                  readinessProbe:
                      httpGet:
                          path: /leaderboards/publishers
                          port: 3003
                      initialDelaySeconds: 5
                      periodSeconds: 5
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "100m"
                      limits:
                          memory: "256Mi"
                          cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
    name: leaderboards-service
    namespace: neighborly
spec:
    selector:
        app: leaderboards
    ports:
        - port: 3003
          targetPort: 3003
    type: ClusterIP
