apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres
    namespace: neighborly
    labels:
        app: postgres
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                - name: postgres
                  image: postgres:16
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_USER
                        valueFrom:
                            configMapKeyRef:
                                name: neighborly-config
                                key: POSTGRES_USER
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: neighborly-secrets
                                key: postgres-password
                      - name: POSTGRES_DB
                        valueFrom:
                            configMapKeyRef:
                                name: neighborly-config
                                key: POSTGRES_DB
                  volumeMounts:
                      - name: postgres-storage
                        mountPath: /var/lib/postgresql/data
                  livenessProbe:
                      exec:
                          command:
                              - pg_isready
                              - -U
                              - postgres
                              - -d
                              - neighborly_reviews
                      initialDelaySeconds: 30
                      periodSeconds: 10
                  readinessProbe:
                      exec:
                          command:
                              - pg_isready
                              - -U
                              - postgres
                              - -d
                              - neighborly_reviews
                      initialDelaySeconds: 5
                      periodSeconds: 5
                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "250m"
                      limits:
                          memory: "512Mi"
                          cpu: "500m"
            volumes:
                - name: postgres-storage
                  persistentVolumeClaim:
                      claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
    name: postgres
    namespace: neighborly
spec:
    selector:
        app: postgres
    ports:
        - port: 5432
          targetPort: 5432
    type: ClusterIP
