apiVersion: v1
kind: PersistentVolume
metadata:
    name: mongo-pv
    namespace: neighborly
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: standard
    hostPath:
        path: /data/mongo

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongo-pvc
    namespace: neighborly
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
    storageClassName: standard

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: postgres-pv
    namespace: neighborly
spec:
    capacity:
        storage: 5Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: standard
    hostPath:
        path: /data/postgres

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-pvc
    namespace: neighborly
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
    storageClassName: standard
