apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongo-pvc
    namespace: neighborly
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-pvc
    namespace: neighborly
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 500Mi
